### ISSUE TITLE
compatibility with `supermaven-nvim` (indent issue)

### ISSUE THREAD

**Issue by theol0403** [Saghen/blink.compat#14] opened 2024-11-25 17:40 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp` and `blink.compat`
- [X] I have read the README

### Bug Description

Supermaven's suggestions seem to expect nvim-cmp to clear the line before inserting the suggestion. For this reason, indentation can double up when accepting the suggestion. 

Cmp:
![image](https://github.com/user-attachments/assets/07a07a89-dd45-43f6-83ea-07a4633634fe)

Blink:
![image](https://github.com/user-attachments/assets/ba95b186-ab6a-4456-8be1-8764cc2a17cd)

### Relevant configuration

```lua
{
  "saghen/blink.cmp",
  opts = {
    sources = {
      compat = { "supermaven" },
    },
    windows = {
      autocomplete = {
        selection = "auto_insert",
      },
    },
  },
  dependencies = {
    "saghen/blink.compat",
    {
      "supermaven-inc/supermaven-nvim",
      opts = {
        keymaps = {
          accept_suggestion = nil,
        },
        disable_inline_completion = true,
      },
    },
  },
},
```

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

v0.6.1

### `blink.compat` version: branch, tag, or commit

0f368c3

**Comment by theol0403** [comment] 2024-11-25 17:45
Something else I noticed:
- with `auto_insert`, but then hitting `enter` after, will delete the entire line
- without `auto_insert`, `accept` simply does nothing other than close the completion window

**Comment by stefanboca** [comment] 2024-11-26 00:04
@theol0403 I believe I know what the issue is. Could you try mannually pinning blink.cmp to `0.5.0` and blink.compat to 0bb4b68e8f09d66ca69f482c6aa782c0f643829b to see if that works?

@Saghen it looks like supermaven [expects](https://github.com/supermaven-inc/supermaven-nvim/blob/07d20fce48a5629686aefb0a7cd4b25e33947d50/lua/supermaven-nvim/cmp.lua#L40-L44) the regular completion to continue after `execute`, which as I understand is different to how blink handles execute. Is this something that could be made configurable by the source (ex by introducing `opts` into the callback parameters)?

For reference, it looks like [nvim-cmp](https://github.com/hrsh7th/nvim-cmp/blob/ed31156aa2cc14e3bc066c59357cc91536a2bc01/lua/cmp/core.lua#L503-L513) always calls execute after completion is finished, and it's not used to allow the source to handle accepting its completion itself.

**Comment by theol0403** [comment] 2024-11-26 14:00
@stefanboca thank you for the reply! unfortunately, I am having trouble downgrading blink.cmp... I am within the LazyVim environment, and while downgrading is possible, there are breaking changes in LazyVim's configuration... and when completely resetting LazyVim's default configuration... supermaven (or LSP for that matter) no longer work out of the box.

I can try to keep debugging a fresh install of blink.cmp outside of the LazyVim context but I am unsure if it is worth the time given that you seem to understand the issue.

**Comment by saghen** [comment] 2024-11-27 21:45
@stefanboca Just pushed the change on `main`, it'll run the `execute` function after applying

**Comment by stefanboca** [comment] 2024-11-27 21:57
@theol0403 could you check if you still have the same issue?

@sagehen thanks, just saw this.
Unrelated but right before I saw this I merged #15 and released v1.0.1 which accidentally included 6d914f7396cf026f04156266a5b134a25cbbca97, so there might be some slight incompatibility until the next release of blink.cmp.

**Comment by saghen** [comment] 2024-11-27 22:03
Reverted the commit and made a new release without it, should be all good now, thanks for noticing

**Comment by theol0403** [comment] 2024-11-28 13:47
@Saghen @stefanboca thanks for the work on this!

With `auto_insert`, the behavior is now improved -- cycling the selections maintains proper indentation! However, hitting `accept` **cancels the entire suggestion** and reverts to an empty line. 

Similarly, without `auto_insert`, hitting `accept` simply closes the completion window without inserting the selected suggestion.

**Comment by stefanboca** [comment] 2024-12-02 18:36
@theol0403 I just installed supermaven to try replicate this issue and I couldn't. Accepting both with and without auto_insert worked fine for me (although there were some errors with ghost text). Here's the config I used:

```lua
{
  "supermaven-inc/supermaven-nvim",
  opts = {
    disable_inline_completion = true,
  },
},
{
  "saghen/blink.cmp",
  opts = {
    sources = {
      completion = {
        enabled_providers = { "supermaven" },
      },
      providers = {
        supermaven = {
          name = "supermaven",
          module = "blink.compat.source",
          score_offset = 3,
        },
      },
    },
  },
},
```

**Closed as completed** 2024-12-02 21:55 UTC
Labels: bug

**Comment by hkhrithik007** [comment] 2025-02-16 12:03
{
    "supermaven-inc/supermaven-nvim",

    event = "InsertEnter",
    keymaps = {
      accept_suggestion = nil,
    },
    opts = {
      disable_inline_completion = true,
    },
  },
  {
    "saghen/blink.cmp",
    event = "InsertEnter",
    lazy = true,
    dependencies = {
      "rafamadriz/friendly-snippets",
      "moyiz/blink-emoji.nvim",
      "mikavilpas/blink-ripgrep.nvim",
      {
        "saghen/blink.compat",
        version = "event",
        opts = {
          enable_events = true,
        },
      },
    },
    config = function()
      require("configs.blink").setup()
    end,
  },
and this is the blink.lua 
local M = {}

function M.setup()
  local blink = require "blink.cmp"
  blink.setup {
    enabled = function()
      local filetype = vim.bo.filetype
      return not vim.tbl_contains({ "TelescopePrompt", "minifiles", "snacks_picker_input" }, filetype)
    end,

    sources = {
      default = { "lsp", "path", "snippets", "buffer", "supermaven" },
      providers = {
        lsp = {
          name = "lsp",
          enabled = true,
          module = "blink.cmp.sources.lsp",
          min_keyword_length = 2,
          score_offset = 90,
        },
        supermaven = {
          name = "supermaven",
          module = "blink.compat.source",
          score_offset = 3,
        },
        path = {
          name = "Path",
          module = "blink.cmp.sources.path",
          score_offset = 25,
          fallbacks = { "snippets", "buffer" },
          min_keyword_length = 2,
          opts = {
            trailing_slash = false,
            label_trailing_slash = true,
            get_cwd = function(context)
              if context and context.bufnr then
                return vim.fn.expand(("#%d:p:h"):format(context.bufnr))
              end
              return vim.fn.getcwd()
            end,
            show_hidden_files_by_default = true,
          },
        },
        buffer = {
          name = "Buffer",
          enabled = true,
          max_items = 3,
          module = "blink.cmp.sources.buffer",
          min_keyword_length = 4,
          score_offset = 15,
        },
        snippets = {
          name = "snippets",
          enabled = true,
          max_items = 15,
          min_keyword_length = 2,
          module = "blink.cmp.sources.snippets",
          score_offset = 85,
        },
        emoji = {
          name = "Emoji",
          module = "blink-emoji",
        },
        ripgrep = {
          name = "Ripgrep",
          module = "blink-ripgrep",
        },
      },
    },

    cmdline = {
      sources = function()
        local type = vim.fn.getcmdtype()
        if type == "/" or type == "?" then
          return { "buffer" }
        elseif type == ":" then
          return { "cmdline" }
        end
        return {}
      end,
    },

    completion = {
      keyword = { range = "full" },
      list = {
        selection = {
          preselect = true, -- ✅ Fixed: Boolean instead of string
          auto_insert = true, -- ✅ Prevents auto-inserting suggestions
        },
      },
      accept = { auto_brackets = { enabled = true } },
      menu = {
        border = "rounded",
        auto_show = true,
        draw = {
          columns = {
            { "label", "label_description", gap = 1 },
            { "kind_icon", "kind" },
          },
        },
      },
      documentation = {
        auto_show = true,
        window = {
          border = "single",
        },
      },
      ghost_text = {
        enabled = false,
      },
    },

    snippets = {
      preset = "luasnip",
      expand = function(snippet)
        local ok, luasnip = pcall(require, "luasnip")
        if ok then
          luasnip.lsp_expand(snippet)
        end
      end,
      active = function(filter)
        local ok, luasnip = pcall(require, "luasnip")
        if ok then
          if filter and filter.direction then
            return luasnip.jumpable(filter.direction)
          end
          return luasnip.in_snippet()
        end
        return false
      end,
      jump = function(direction)
        local ok, luasnip = pcall(require, "luasnip")
        if ok then
          luasnip.jump(direction)
        end
      end,
    },

    keymap = {
      preset = "enter",
      ["<Tab>"] = { "snippet_forward", "fallback" },
      ["<S-Tab>"] = { "snippet_backward", "fallback" },
      ["<Up>"] = { "select_prev", "fallback" },
      ["<Down>"] = { "select_next", "fallback" },
      ["<C-p>"] = { "select_prev", "fallback" },
      ["<C-n>"] = { "select_next", "fallback" },
      ["<S-k>"] = { "scroll_documentation_up", "fallback" },
      ["<S-j>"] = { "scroll_documentation_down", "fallback" },
      ["<C-space>"] = { "show", "show_documentation", "hide_documentation" },
      ["<C-e>"] = { "hide", "fallback" },
    },

    appearance = {
      use_nvim_cmp_as_default = true,
      nerd_font_variant = "Normal",
    },
    signature = { enabled = true, window = { border = "rounded" } },
  }
end

return M

**Comment by hkhrithik007** [comment] 2025-02-16 12:03
not working for me

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/f8963ce2-29a0-4a6d-896a-5297fd6f2b9b" />
